root_dir: '/home/runshengxu/project/OpenCOOD/opv2v_data_dumping/test'
output_dir: '/home/runshengxu/project/OpenCOOD/opv2v_data_dumping/additional/test'
map: # corresponding to bev map
  activate: true
  visualize: true
  radius: 50 # meter
  raster_size: [256, 256]
  lane_sample_resolution: 0.1
  static:
    draw_lane: false
    draw_traffic_light: true
    exclude_road: true
  dynamic:
    exclude_self: true

sensor: # new attached sensor
  sensor_list:
    - name: 'bev_semantic_camera'
      args:
        visualize: true
        fov: 45
        image_size_x: 512
        image_size_y: 512
        height: 100

